name: study_is_good
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  firebase_messaging: ^14.6.5
  flutter_signin_button: ^2.0.0
  google_sign_in: ^6.1.4
  flutter_background_service: ^5.0.1
  device_info_plus: ^9.0.3
  flutter_local_notifications: ^15.1.1
  shared_preferences: ^2.2.1
  timezone: ^0.9.2
  flutter_timezone: ^1.0.7
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.7
  provider: ^6.1.0
  just_audio: ^0.9.35
  just_audio_background: ^0.0.1-beta.11
  rxdart: ^0.27.7
  audio_session: ^0.1.16
  go_router: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true































