// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwQb5jrBTwKeaWBZUcVPQYyW6TEH9IkXk',
    appId: '1:877728621082:web:19999e0ed8c428aef327a3',
    messagingSenderId: '877728621082',
    projectId: 'reading-extension-175ab',
    authDomain: 'reading-extension-175ab.firebaseapp.com',
    databaseURL: 'https://reading-extension-175ab-default-rtdb.firebaseio.com',
    storageBucket: 'reading-extension-175ab.appspot.com',
    measurementId: 'G-DPQPZ62LFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxWW-jdyQOGkR172t1aOE4hFKNJS9fDVw',
    appId: '1:877728621082:android:0944b76fa056cd96f327a3',
    messagingSenderId: '877728621082',
    projectId: 'reading-extension-175ab',
    databaseURL: 'https://reading-extension-175ab-default-rtdb.firebaseio.com',
    storageBucket: 'reading-extension-175ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxUNUfsap7OcVba0LYP-h6ztg1CLjongA',
    appId: '1:877728621082:ios:de0df023cdedede4f327a3',
    messagingSenderId: '877728621082',
    projectId: 'reading-extension-175ab',
    databaseURL: 'https://reading-extension-175ab-default-rtdb.firebaseio.com',
    storageBucket: 'reading-extension-175ab.appspot.com',
    iosClientId: '877728621082-ll2t4meg6vcpo37gi6i0tenuh0d13ich.apps.googleusercontent.com',
    iosBundleId: 'com.codingminds.studyIsGood',
  );
}
